default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: first_app_development

test:
  <<: *default
  database: first_app_test

production:
  <<: *default
  database: first_app_production
  username: first_app
  password: <%= ENV['FIRST_APP_DATABASE_PASSWORD'] %>
